name: Terraform Apply

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desarrollo:
    name: TF plan & apply Desarrollo
    runs-on: ubuntu-latest
    environment: desarrollo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: ./.github/actions/azure-login

    - name: Terraform Init and Workspace
      uses: ./.github/actions/terraform-init-and-workspace
      with:
        workspace-name: ${{ github.job }}
        backend-tfvars: ${{ vars.BACKEND_TFVARS }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan-${{ github.job }}

    - name: Upload Terraform Plan as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-${{ github.job }}
        path: tfplan-${{ github.job }}
        retention-days: 30

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan-${{ github.job }}

  plan-produccion:
    name: TF plan Produccion
    runs-on: ubuntu-latest
    needs: desarrollo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: ./.github/actions/azure-login

    - name: Terraform Init and Workspace
      uses: ./.github/actions/terraform-init-and-workspace
      with:
        workspace-name: produccion
        backend-tfvars: ${{ vars.BACKEND_TFVARS }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan-produccion

    - name: Upload Terraform Plan as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-produccion
        path: tfplan-produccion
        retention-days: 30

  produccion:
    name: TF apply Produccion
    runs-on: ubuntu-latest
    needs: plan-produccion
    environment: produccion

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: ./.github/actions/azure-login

    - name: Terraform Init and Workspace
      uses: ./.github/actions/terraform-init-and-workspace
      with:
        workspace-name: ${{ github.job }}
        backend-tfvars: ${{ vars.BACKEND_TFVARS }}

    - name: Download Terraform Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: tfplan-produccion
        path: .

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan-produccion
