name: Terraform Init

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-init:
    name: Terraform Init
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Azure CLI
      shell: bash
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure Login with Device Code
      shell: bash
      run: |
        echo "Starting Azure login with device code..."
        echo "You will see a code and URL below. Open the URL in your browser and enter the code to authenticate."
        echo ""
        az login --use-device-code
        echo ""
        echo "Azure login successful!"
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.0
    
    - name: Create backend config
      run: |
        cat << 'EOF' > backend.tfvars
        ${{ vars.BACKEND_TFVARS }}
        EOF
    
    - name: Terraform Init
      run: terraform init -backend-config=backend.tfvars

    - name: Terraform Plan
      run: terraform plan